;opis dla kabla
(defun c:@op ()
  (vl-load-com)
  (setq ss (ssget))
  (setq $ent_ename (ssname ss 0))
  (setq $ent_data (entget $ent_ename))
  (setq $text (cdr (assoc '304 $ent_data)))
  (setq x1 (strcat "d�. tras. " (getstring "d�. tras:") "m"))
  (setq x2 (strcat "d�. inst. " (getstring "d�. inst:") "m"))
	(setq x3 (strcat "d�. opt. " (getstring "d�. opt:") "m"))
  (setq $newText (vl-string-subst x1 "d�. tras. _" $text))
  (setq $newText2 (vl-string-subst x2 "d�. inst. _" $newText))
  (setq $newText3 (vl-string-subst x3 "d�. opt. _" $newText2))
	(setq $VAL (subst (cons 304 $newText3) (assoc 304 $ent_data) $ent_data))
  (entmod $VAL)
  (entupd $ent_ename)
)
(defun c:@op2 ()
  (vl-load-com)
  (setq ss (ssget))
  (setq $ent_ename (ssname ss 0))
  (setq $ent_data (entget $ent_ename))
  (setq $text (cdr (assoc '1 $ent_data)))
  (setq x1 (strcat "d�. tras. " (getstring "d�. tras:") "m"))
  (setq x2 (strcat "d�. inst. " (getstring "d�. inst:") "m"))
	(setq x3 (strcat "d�. opt. " (getstring "d�. opt:") "m"))
  (setq $newText (vl-string-subst x1 "d�. tras. _" $text))
  (setq $newText2 (vl-string-subst x2 "d�. inst. _" $newText))
  (setq $newText3 (vl-string-subst x3 "d�. opt. _" $newText2))
	(setq $VAL (subst (cons 1 $newText3) (assoc 1 $ent_data) $ent_data))
  (entmod $VAL)
  (entupd $ent_ename)
)

